version: 0.1
phases:
  build:
    runtime-versions:
      nodejs: 8
    commands:
      - echo "Nothing to do yet"
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/*
    - images/*
  